Repository de-souza-capstone-2020/Mars, pull requests merged in 2020-03, with the labels that each got.

#88 welcome page now uses states
  screens/welcome.js
Labels: Welcome Flow UI

#86 fixed bug
  screens/chat-screen/home.js
Labels: bug, conversation flow chat for chapter 1

#93 Feature/better welcomepage
  screens/data/logo.png
  screens/welcome.js
Labels: Beautify Application

#102 revamped history ui
  screens/chat-screen/history.js
  screens/chat-screen/styles.js
Labels: Beautify Application

#106 Feature/better onboarding
  assets/onboarding.png
  assets/onboarding2.png
  screens/intro.js
  screens/welcome.js
Labels: Beautify Application

#111 Ordered Tips/Messages + Generic tips
  screens/SleepDiaryEdit.js
  screens/chat-screen/home.js
  screens/data/customActions.js
  screens/data/messages.js
  screens/utils/helper-utils.js
Labels: Sleep Diary Tips

#119 Feature/better onboarding
  assets/onboarding.png
  assets/onboarding2.png
  screens/intro.js
  screens/welcome.js
Labels: Beautify Application
